version: '3'

services:
  backend:
    build: ./backend
    environment:
      - FRONTEND_URL= http://192.168.99.100:80
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      - API_URL= http://192.168.99.100:8000
    ports:
      - "80:80"