version: '3'
# FRONTEND_URL 和 API_URL 还需要改动
services:
  backend:
    build: 
      context: ./backend
    environment:
      - FRONTEND_URL=http://192.168.99.100 # 加上 80 端口反而无法跨域
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      args:
        API_URL: http://192.168.99.100:8000 # 通过 --build-arg 实现，如需修改带上 --build 重建容器
    ports:
      - "80:80" # 这个不能删